# Generated by Django 2.1.5 on 2020-01-08 03:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200102_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify',
            field=models.BooleanField(default=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
