# Generated by Django 2.1.5 on 2020-01-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='diggs',
            field=models.IntegerField(default=0),
        ),
    ]
