# Generated by Django 2.1.5 on 2020-01-03 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_post_diggs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diggs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digg', models.ManyToManyField(default=0, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='diggs',
        ),
    ]
