# Generated by Django 2.1.5 on 2020-01-03 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20200103_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diggs',
            name='digg',
        ),
        migrations.AddField(
            model_name='diggs',
            name='responder',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
