# Generated by Django 2.1.5 on 2020-01-03 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20200103_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diggs',
            name='responder',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Diggs',
        ),
    ]
