# Generated by Django 2.1.5 on 2020-01-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200103_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_by',
            new_name='liked_by',
        ),
    ]
