# Generated by Django 2.1.5 on 2020-01-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='geek',
        ),
    ]
