# Generated by Django 2.1.5 on 2020-01-04 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20200103_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='geek',
            field=models.ManyToManyField(default='', related_name='geek', to=settings.AUTH_USER_MODEL),
        ),
    ]
