# Generated by Django 2.1.5 on 2020-01-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200104_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='geek',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
