# Generated by Django 2.1.5 on 2020-01-08 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_post_history_update_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
