# Generated by Django 2.1.5 on 2020-01-04 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_list',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
