# Generated by Django 2.1.5 on 2020-01-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0002_auto_20200104_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow_list',
            old_name='followed_by',
            new_name='follow',
        ),
    ]
